const questions = [
{q:'Before touching a patient, what should a healthcare worker do?', options:['Perform hand hygiene','Wait until the end of the visit','Use gloves instead of hand hygiene'],answer:0,why:'Hand hygiene is required immediately before patient contact. Gloves do not replace it.'},
{q:'Your hands are visibly soiled. Which method should you use?',options:['Wipe them on a clean towel','Wash with soap and water','Put on a second pair of gloves'],answer:1,why:'CDC recommends soap and water when hands are visibly soiled.'},
{q:'After removing gloves, what is the next hand-hygiene step?',options:['No additional step is needed','Wait until hands feel dirty','Perform hand hygiene'],answer:2,why:'Perform hand hygiene immediately after glove removal.'},
{q:'A patient asks about a possible medicine interaction. What is the best next step?',options:['Assume nonprescription medicines cannot interact','Check with a pharmacist or appropriate healthcare professional','Advise taking both at the same time'],answer:1,why:'Medicines can interact with other drugs, foods and supplements. A pharmacist or healthcare professional can help clarify risks.'},
{q:'The instructions on a medicine label are unclear. What should the patient do?',options:['Ask a pharmacist or healthcare professional before using it','Guess based on a previous prescription','Ignore the label'],answer:0,why:'Read the label and ask a pharmacist or healthcare professional if instructions remain unclear.'}
];
let current=0;const answers=Array(questions.length).fill(null);const app=document.querySelector('#app');
function render(){const q=questions[current];app.innerHTML=`<form class="card" novalidate><div class="progress-label"><span>Question ${current+1} of ${questions.length}</span><span>Nursing foundations</span></div><progress aria-label="Assessment progress" value="${current}" max="5"></progress><fieldset><legend tabindex="-1">${q.q}</legend>${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[current]===i?'checked':''}><span>${o}</span></label>`).join('')}</fieldset><p class="error" role="alert"></p><div class="quiz-actions"><button class="secondary" type="button" id="previous" ${current===0?'disabled':''}>Back</button><button class="gold" type="submit">${current===4?'See results':'Next question'} →</button></div></form>`;app.querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>{answers[current]=Number(i.value);app.querySelector('.error').textContent=''}));app.querySelector('#previous').onclick=()=>{current--;render();app.querySelector('legend').focus()};app.querySelector('form').onsubmit=e=>{e.preventDefault();if(answers[current]===null){app.querySelector('.error').textContent='Choose an answer to continue.';return}if(current<4){current++;render();app.querySelector('legend').focus()}else result()};}
function result(){const score=questions.reduce((n,q,i)=>n+(answers[i]===q.answer),0);const advice=score<4?'Start with the foundations':'Reinforce your foundation';app.innerHTML=`<section class="card result"><p class="eyebrow">ASSESSMENT COMPLETE</p><h2 tabindex="-1">Your next chapter starts here.</h2><div class="score">${score} / 5</div><p>${score<4?'Review the explanations below, then use the study guide to revisit the core safety principles.':'You answered most or all questions correctly. Use the study guide for a quick review and keep practicing.'}</p><div class="resource"><p class="eyebrow">RECOMMENDED STUDY MATERIAL</p><h3>${advice}</h3><p>Nursing Foundations: Safety Essentials<br>One-page PDF · Hand hygiene and medication awareness</p><a class="gold" href="assets/nursing-foundations.pdf" target="_blank" rel="noopener">View study PDF ↗</a><p class="note">This demo includes one sample guide. Your score determines the review recommendation.</p></div><h2>Review your answers</h2>${questions.map((q,i)=>`<article class="review"><h3>${i+1}. ${q.q}</h3><p><strong>${answers[i]===q.answer?'Correct':'Needs review'}</strong> · Your answer: ${q.options[answers[i]]}</p><p>Correct answer: ${q.options[q.answer]}<br>${q.why}</p></article>`).join('')}<div class="result-actions"><button id="retry" class="secondary">Try again</button><a href="index.html">Back to home</a></div><p class="sources">References: <a href="https://www.cdc.gov/infection-control/hcp/core-practices/" target="_blank" rel="noopener">CDC infection prevention practices</a> · <a href="https://www.fda.gov/drugs/resources-drugs/drug-interactions-what-you-should-know" target="_blank" rel="noopener">FDA drug interaction guidance</a>.</p></section>`;app.querySelector('h2').focus();document.querySelector('#retry').onclick=()=>{answers.fill(null);current=0;render();app.querySelector('legend').focus()};}
render();
